### ISSUE TITLE
Segmentation Fault Serial Version

### ISSUE THREAD

**Issue by diegolaraujo** [teodorst/app-huffman#1]
The serial version has a code slightly different from the OpenMP version and has a segmentation fault when trying to compress file, but ok. If I remove the omp.h library from the OpenMP version I get the same as a serial code, right? But when measuring the time of these two versions, it seems to me that there is no gain in the version paralleled with OpenMP.

**Comment by teodorst** [comment]
This project was for school and for better results I loaded the entire file in RAM. This is probably the main reason why you are getting a segmentation fault (you have to run "ulimit -s unlimited" for maximum resources, again this is only for a school homework). As I remember from homework presentation I had 2/3 of the serial time with parallel code(with OpenMP).
